import one from './resources/img/1.jpg';
import two from './resources/img/2.jpg';
import three from './resources/img/3.jpg';
import four from './resources/img/4.jpg';
import five from './resources/img/5.jpg';
import six from './resources/img/6.jpg';
import seven from './resources/img/7.jpg';
import eight from './resources/img/8.jpg';
import nine from './resources/img/9.jpg';

export const formFilmCreation = [
  {
    label: '',
    id: '',
    labelClassName: '',
    inputClassName: '',
  },
];

export const defaultSchedule = [
  {
    id: 1,
    time: '10:00',
    hall: 'Зал 10',
    type: '2D',
    price: '380р',
  },
  {
    id: 2,
    time: '10:45',
    hall: 'Зал 7',
    type: '2D',
    price: '280р',
  },
  {
    id: 3,
    time: '13:00',
    hall: 'Зал 10',
    type: '2D',
    price: '300р',
  },
  {
    id: 4,
    time: '13:30',
    hall: 'Зал 7',
    type: '2D',
    price: '300р',
  },
  {
    id: 5,
    time: '16:15',
    hall: 'Зал 10',
    type: '2D',
    price: '330р',
  },
  {
    id: 6,
    time: '17:35',
    hall: 'Зал 7',
    type: '2D',
    price: '380р',
  },
  {
    id: 7,
    time: '19:45',
    hall: 'Зал 10',
    type: '2D',
    price: '380р',
  },
  {
    id: 8,
    time: '20:20',
    hall: 'Зал 7',
    type: '2D',
    price: '420р',
  },
  {
    id: 9,
    time: '22:30',
    hall: 'Зал 10',
    type: '2D',
    price: '450р',
  },
];

export const films = [
  {
    id: 1,
    src: one,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '16+',
    name: 'Название фильма 1',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 2,
    src: two,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '16+',
    name: 'Название фильма 2',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 3,
    src: three,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '12+',
    name: 'Название фильма 3',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 4,
    src: four,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '18+',
    name: 'Название фильма 4',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 5,
    src: five,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '12+',
    name: 'Название фильма 5',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 6,
    src: six,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '16+',
    name: 'Название фильма 6',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 7,
    src: seven,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '18+',
    name: 'Название фильма 7',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 8,
    src: eight,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '6+',
    name: 'Название фильма 8',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
  {
    id: 9,
    src: nine,
    timeLength: '2 часа 35 минут',
    imdb: '5.5/10',
    age: '12+',
    name: 'Название фильма 9',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi aut soluta itaque corporis sed sit alias, iusto, fugit facilis sint doloribus. Excepturi dolore enim adipisci aperiam voluptatibus consequuntur modi asperiores.',
    genres: 'Что-то, что-то с чем-то, крутой жанр',
    directors: 'Кто-то, кто-то очень крутой',
    mainRoles: 'aboba',
    selected: false,
  },
];
